#!/bin/bash

PORT=${1:-5555}
BASE_DIR=$(dirname $(cd $(dirname $0); pwd))
BUILD_DIR=$BASE_DIR/_build

export PORT

rm -rf $BUILD_DIR
mkdir $BUILD_DIR $BUILD_DIR/logs $BUILD_DIR/html

cp -rf $BASE_DIR/conf/* $BUILD_DIR/
cp -rf $BASE_DIR/html/* $BUILD_DIR/html

erb $BASE_DIR/conf/nginx.conf.erb > $BUILD_DIR/nginx.conf

echo "Nginx server running on $PORT..."
/usr/local/sbin/nginx -c $BUILD_DIR/nginx.conf -p $BUILD_DIR/
